version: '3'
services:
    app:
        container_name: backend
        build:
          context: ./
          dockerfile: docker/app/Dockerfile
        working_dir: /var/www/
        restart: always
        volumes:
            - ./:/var/www/
        depends_on:
          - db
    web:
      container_name: nginx
      hostname: bnbbank.localhost
      build:
        context: ./
        dockerfile: docker/web/Dockerfile
      restart: always
      tty: true
      ports:
        - "81:80"
      volumes:
        - ./:/var/www
      depends_on:
        - app
    db:
      container_name: mysql
      build:
        context: ./
        dockerfile: docker/db/Dockerfile
      ports:
          - "3306:3306"
      volumes:
           - ./docker/db/dbdata:/var/lib/mysql
      environment:
          - MYSQL_DATABASE=bnbbank
          - MYSQL_ROOT_PASSWORD=root

